call mingw-gcc/rmath_bessel.bat
call mingw-gcc/rmath_beta.bat
call mingw-gcc/rmath_beta_p.bat
call mingw-gcc/rmath_cbrt.bat
call mingw-gcc/rmath_ci.bat
call mingw-gcc/rmath_cos1.bat
call mingw-gcc/rmath_cosacos.bat
call mingw-gcc/rmath_coshacosh.bat
call mingw-gcc/rmath_cotacot.bat
call mingw-gcc/rmath_cothacoth.bat
call mingw-gcc/rmath_cscacsc.bat
call mingw-gcc/rmath_cschacsch.bat
call mingw-gcc/rmath_ei.bat
call mingw-gcc/rmath_erf.bat
call mingw-gcc/rmath_erfc.bat
call mingw-gcc/rmath_erfinv.bat
call mingw-gcc/rmath_exp.bat
call mingw-gcc/rmath_exp2.bat
call mingw-gcc/rmath_expm1.bat
call mingw-gcc/rmath_frexp.bat
call mingw-gcc/rmath_gamma.bat
call mingw-gcc/rmath_gammaincr.bat
call mingw-gcc/rmath_gamma_p.bat
call mingw-gcc/rmath_hypot.bat
call mingw-gcc/rmath_lbeta.bat
call mingw-gcc/rmath_ldexp.bat
call mingw-gcc/rmath_lgamma.bat
call mingw-gcc/rmath_li.bat
call mingw-gcc/rmath_log.bat
call mingw-gcc/rmath_log10.bat
call mingw-gcc/rmath_log1p.bat
call mingw-gcc/rmath_log2.bat
call mingw-gcc/rmath_modf.bat
call mingw-gcc/rmath_quadrant.bat
call mingw-gcc/rmath_riemann_zeta.bat
call mingw-gcc/rmath_secasec.bat
call mingw-gcc/rmath_sechasech.bat
call mingw-gcc/rmath_si.bat
call mingw-gcc/rmath_sinasin.bat
call mingw-gcc/rmath_sinc.bat
call mingw-gcc/rmath_sinhasinh.bat
call mingw-gcc/rmath_sqrt.bat
call mingw-gcc/rmath_tanatan.bat
call mingw-gcc/rmath_tanhatanh.bat
