# ---- for GNU gcc ----

CC := gcc

CFLAGS := -Wall -DUSE_FFT2D_WINTHREADS -DUSE_FFT3D_WINHREADS

OFLAGS := -O2

INCLUDE := -I../include



all: fftsg2dt_wt fftsg3dt_wt


fftsg2dt_wt : fftsg2dt.o fftsg2dpt.o fftsg.o alloc.o
	$(CC) fftsg2dt.o fftsg2dpt.o fftsg.o alloc.o -lm -lpthread -o fftsg2dt_wt

fftsg3dt_wt : fftsg3dt.o fftsg3dpt.o fftsg.o alloc.o
	$(CC) fftsg3dt.o fftsg3dpt.o fftsg.o alloc.o -lm -lpthread -o fftsg3dt_wt


fftsg2dt.o : fftsg2dt.c
	$(CC) $(CFLAGS) $(OFLAGS) $(INCLUDE) -c fftsg2dt.c -o fftsg2dt.o

fftsg3dt.o : fftsg3dt.c
	$(CC) $(CFLAGS) $(OFLAGS) $(INCLUDE) -c fftsg3dt.c -o fftsg3dt.o


fftsg2dpt.o : ../src/fftsg2d.c
	$(CC) $(CFLAGS) $(OFLAGS) $(INCLUDE) -c ../src/fftsg2d.c -o fftsg2dpt.o

fftsg3dpt.o : ../src/fftsg3d.c
	$(CC) $(CFLAGS) $(OFLAGS) $(INCLUDE) -c ../src/fftsg3d.c -o fftsg3dpt.o

fftsg.o : ../src/fftsg.c
	$(CC) $(CFLAGS) $(OFLAGS) $(INCLUDE) -c ../src/fftsg.c -o fftsg.o

alloc.o : ../src/alloc.c
	$(CC) $(CFLAGS) $(OFLAGS) $(INCLUDE) -c ../src/alloc.c -o alloc.o




clean:
	rm -f *.o

